# Generated by Django 3.0.4 on 2020-04-02 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id_event', models.IntegerField(primary_key=True, serialize=False)),
                ('name_event', models.CharField(blank=True, max_length=200, null=True)),
                ('document', models.CharField(blank=True, max_length=400, null=True)),
                ('logo', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id_type', models.IntegerField(primary_key=True, serialize=False)),
                ('name_type', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'event_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id_level', models.IntegerField(primary_key=True, serialize=False)),
                ('name_level', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'level',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('login', models.OneToOneField(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name_org', models.CharField(blank=True, max_length=400, null=True)),
                ('short_name_org', models.CharField(blank=True, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('full_name_head', models.CharField(blank=True, max_length=50, null=True)),
                ('email_org', models.CharField(blank=True, max_length=30, null=True)),
                ('phone_org', models.CharField(blank=True, max_length=12, null=True)),
                ('inn', models.BigIntegerField(blank=True, db_column='INN', null=True)),
                ('ogrn_ogrnip', models.BigIntegerField(blank=True, db_column='OGRN/OGRNIP', null=True)),
            ],
            options={
                'db_table': 'organizer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('login', models.OneToOneField(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name_part', models.CharField(blank=True, max_length=60, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('email_part', models.CharField(blank=True, max_length=30, null=True)),
                ('passport', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_part', models.CharField(blank=True, max_length=12, null=True)),
            ],
            options={
                'db_table': 'participant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id_purpose', models.IntegerField(primary_key=True, serialize=False)),
                ('name_purpose', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'purpose',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id_notice', models.IntegerField(primary_key=True, serialize=False)),
                ('date_notice', models.DateField(blank=True, null=True)),
                ('max_part', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_n', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('id_event', models.ForeignKey(blank=True, db_column='id_event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Event')),
                ('id_purpose', models.ForeignKey(blank=True, db_column='id_purpose', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Purpose')),
            ],
            options={
                'db_table': 'notice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id_news', models.IntegerField(primary_key=True, serialize=False)),
                ('information', models.TextField(blank=True, null=True)),
                ('photos', models.CharField(blank=True, max_length=200, null=True)),
                ('date_news', models.DateField(blank=True, null=True)),
                ('id_notice', models.ForeignKey(blank=True, db_column='id_notice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Notice')),
            ],
            options={
                'db_table': 'news',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='event',
            name='id_level',
            field=models.ForeignKey(blank=True, db_column='id_level', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Level'),
        ),
        migrations.AddField(
            model_name='event',
            name='id_type',
            field=models.ForeignKey(blank=True, db_column='id_type', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.EventType'),
        ),
        migrations.AddField(
            model_name='event',
            name='login',
            field=models.ForeignKey(blank=True, db_column='login', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Organizer'),
        ),
        migrations.CreateModel(
            name='ListPart',
            fields=[
                ('login', models.OneToOneField(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.Participant')),
                ('date_record', models.DateField(blank=True, null=True)),
                ('id_notice', models.ForeignKey(db_column='id_notice', on_delete=django.db.models.deletion.DO_NOTHING, to='service.Notice')),
            ],
            options={
                'db_table': 'list_part',
                'managed': True,
                'unique_together': {('login', 'id_notice')},
            },
        ),
    ]
