# Generated by Django 3.0.4 on 2020-04-22 09:02

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photos',
            # field=models.ImageField(blank=True, null=True, upload_to=service.models.get_image_path),
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
