# Generated by Django 3.0.4 on 2020-04-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200422_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='event_docs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='event'),
        ),
    ]
