# Generated by Django 3.0.4 on 2020-04-26 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_auto_20200426_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listpart',
            name='login',
            field=models.ForeignKey(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.Participant'),
        ),
    ]
