# Generated by Django 3.0.4 on 2020-05-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20200426_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_criteria', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.FloatField()),
                ('maximum', models.IntegerField()),
                ('minimum', models.IntegerField()),
            ],
            options={
                'db_table': 'criteria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('login', models.ForeignKey(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='service.Participant')),
                ('id_criteria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Criteria')),
                ('id_notice', models.ForeignKey(blank=True, db_column='id_notice', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Notice')),
            ],
            options={
                'db_table': 'rating',
                'managed': True,
            },
        ),
    ]
