# Generated by Django 3.0.4 on 2020-05-10 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_rating_evaluation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('login', 'id_notice'), ('login', 'id_criteria')},
        ),
    ]
