# Generated by Django 3.0.4 on 2020-05-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20200510_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('login', 'id_notice', 'id_criteria')},
        ),
    ]
