# Generated by Django 3.0.4 on 2020-05-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20200510_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='login',
            field=models.ForeignKey(blank=True, db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, to='service.Participant'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
