# Generated by Django 3.0.4 on 2020-05-10 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20200510_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='listpart',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listpart',
            name='login',
            field=models.ForeignKey(db_column='login', on_delete=django.db.models.deletion.DO_NOTHING, to='service.Participant'),
        ),
    ]
